# Generated by Django 6.0.3 on 2026-03-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('new_input_price', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('new_current_price', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('new_wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
